### ISSUE TITLE
Consider files with only blank lines as empty too

### ISSUE THREAD

**Issue by davidesner** [keboola/processor-remove-empty-files-and-folders#2]
A file that contains only single new line character is not considered as empty. It would be nice if the processor could somehow recognise that. Perhaps iterate through file until there is `strlen(trim($line))==0` and if the eof is reached its empty.

**Comment by odinuv** [comment]
makes sense to me,  @ondrejhlavacek opinion ?

**Comment by ondrejhlavacek** [comment]
Yes, it can be the default behavior. 

How many whitespaces will we consider? 100 windows newlines is an empty file of 200 bytes. I would like to avoid reading all files.
